# Defines
COMPILER = cl.exe
INCLUDES = .\src\find_process_id.c

# Compile, test and clean
all: objects program test

# Compile object
objects:
	$(COMPILER) /LD -c $(INCLUDES) /Fo:find_process_id.obj

# Compile `test.c`
program:
	$(COMPILER) .\test.c .\find_process_id.obj /Fe:test.exe
	del test.obj

# Test `test.exe`
test:
	.\test.exe

# Clean all build files
clean:
	del /Q *.exe *.a *.o *.obj *.lib *.dll *.pdb
