# Defines
COMPILER = cl.exe
INCLUDES = .\src\http_request.c

# Compile, test and clean
all: objects program test

# Compile object
objects:
	$(COMPILER) /LD -c $(INCLUDES) /Fo:http_request.obj

# Compile `test.c`
program:
	$(COMPILER) .\test.c .\http_request.obj /Fe:test.exe
	del test.obj

# Test `test.exe`
test:
	.\test.exe

# Clean all build files
clean:
	del /Q *.exe *.a *.o *.obj *.lib *.dll *.pdb
