name: Compile & test using `nmake`, then publish

permissions:
  contents: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Compile
        run: nmake /A /f makefile.msvc
      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - name: Release 
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.SHORT_SHA }}
          files: ./modules/*/*.obj
          tag_name: tag-${{ env.SHORT_SHA }}