name: Compile & test using `nmake`, then publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: Compile
      run: nmake /A /f makefile.msvc
    - name: Release ${{ github.sha }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          modules/*/*.obj