name: Compile & test using `nmake`

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: nmake
      run: nmake /A /f makefile.msvc
