name: Compile & test using `nmake`, then publish

permissions:
  contents: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Get short SHA hash
        id: hash
        run: |
          echo "{hash}={$(git rev-parse --short HEAD)}" >> $GITHUB_STATE
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Compile
        run: nmake /A /f makefile.msvc
      - name: Release 
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.date }}-${{ env.hash }}
          files: ./modules/*/*.obj
          tag_name: ${{ env.date }}-${{ env.hash }}